package usuario.view;

import funcionario.FuncionarioBean;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import usuario.bean.UsuarioBean;
import usuario.dao.UsuarioDao;
import professor.bean.ProfessorBean;
import professor.dao.ProfessorDao;
import perfil.bean.PerfilBean;
import perfil.dao.PerfilDao;
import util.DaoException;
import util.FrameWork;

/**
 *
 * @author GRUPO KERNEL
 */
public class JIFCadastroUsuario extends javax.swing.JInternalFrame {

    private UsuarioDao usuarioDao = null;
    private ProfessorDao professorDao = null;

    /**
     * Creates new form JIFCadastroUsuario
     */
    public JIFCadastroUsuario() {
        initComponents();
        
        if (usuarioDao == null) {
            usuarioDao = new UsuarioDao();
        }
        if (professorDao == null) {
            professorDao = new ProfessorDao();
        }
        
        try {
            jCBFuncionario.setModel(new DefaultComboBoxModel(professorDao.listar().toArray()));
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
        try {
            jCBPerfil.setModel(new DefaultComboBoxModel(new PerfilDao().listar().toArray()));
        } catch (DaoException ex) {
            Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        limpar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBCadastrar = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCBFuncionario = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jPFConfirmarSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jCBPerfil = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Cadastro de Usuário");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBCadastrar.setMnemonic('c');
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBPesquisar.setMnemonic('p');
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBLimpar.setMnemonic('l');
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBExcluir.setMnemonic('e');
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBFechar.setMnemonic('f');
        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jBAlterar.setMnemonic('a');
        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
            .addComponent(jBPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jBCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBFechar)
                .addGap(5, 5, 5))
        );

        jCBFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Funcionário*:");

        jLabel3.setText("Senha*:");

        jLabel4.setText("Confirmar senha*:");

        jLabel2.setText("Usuário*:");

        jLabel5.setText("Código:");

        jTFCodigo.setEditable(false);

        jCBPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Perfil*:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPFConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(jCBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPFConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        fechar();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jCBFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBFuncionarioActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        selecionar();
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_jBAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JComboBox jCBFuncionario;
    private javax.swing.JComboBox jCBPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFConfirmarSenha;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        jTFCodigo.setText("");
        jCBFuncionario.setSelectedIndex(-1);
        jCBPerfil.setSelectedIndex(-1);
        jTFUsuario.setText("");
        jPFSenha.setText("");
        jPFConfirmarSenha.setText("");
    }
    
    private void fechar() {
        if (verificaPreenchido()) {
            int o = JOptionPane.showConfirmDialog(this, "Há dados preenchidos! Deseja realmente sair?", "Mensagem", JOptionPane.YES_OPTION);
            if (o == 0) {
                dispose();
            }
        } else {
            dispose();
        }
    }
    
    /**
     *
     * @return Retorna true se algum campo estiver preenchido e false caso
     * contrário.
     */
    private boolean verificaPreenchido() {
        if (!(jCBFuncionario.getSelectedIndex() == -1) ||
                !(jCBPerfil.getSelectedIndex() == -1) ||
                !(jTFUsuario.getText().isEmpty()) ||
                !(jPFSenha.getText().isEmpty()) ||
                !(jPFConfirmarSenha.getText().isEmpty())) {
            return true;
        } else {
            return false;
        }
    }

    private void cadastrar() {
        UsuarioBean usuario = populaUsuarioBean();

        if (usuario != null) {
            try {
                if (usuarioDao.inserir(usuario) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso!");
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar!");
                }
            } catch (DaoException ex) {
                Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private UsuarioBean populaUsuarioBean() {
        UsuarioBean usuario;

        if (validaLogin()) {
            FuncionarioBean funcionario = (FuncionarioBean) jCBFuncionario.getSelectedItem();
            PerfilBean perfil = (PerfilBean) jCBPerfil.getSelectedItem();

            usuario = new UsuarioBean();
            usuario.setPerfil(perfil);
            usuario.setFuncionario(funcionario);
            usuario.setUsuario(jTFUsuario.getText());
            usuario.setSenha(FrameWork.criptografar(jPFSenha.getText()));

            return usuario;
        }
        return null;
    }

    private boolean validaLogin() {
        if (jCBFuncionario.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário");
            jCBFuncionario.grabFocus();
            return false;
        } else if (jCBPerfil.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Perfil");
            jCBPerfil.grabFocus();
            return false;
        } else if (jTFUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo usuário obrigatório!");
            jTFUsuario.grabFocus();
            return false;
        } else if (jPFSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo senha obrigatório!");
            jPFSenha.grabFocus();
            return false;
        } else if (jPFConfirmarSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Campo confirma senha obrigatório!");
            jPFConfirmarSenha.grabFocus();
            return false;
        } else if (!jPFSenha.getText().equals(jPFConfirmarSenha.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Senhas não conferem!");
            limparSenhas();
            jPFSenha.grabFocus();
            return false;
        }
        return true;
    }

    private void limparSenhas() {
        jPFSenha.setText("");
        jPFConfirmarSenha.setText("");
    }

    private void excluir() {
        if (!jTFCodigo.getText().isEmpty()) {
            int codigo = Integer.parseInt(jTFCodigo.getText());
            try {
                if (usuarioDao.excluir(codigo)) {
                    JOptionPane.showMessageDialog(rootPane, "Usuário excluído!");
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!");
                }
            } catch (DaoException ex) {
                Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!");
        }
    }

    private void selecionar() {
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Informe o código do usuário."));
        try {
            UsuarioBean usuario = (UsuarioBean) usuarioDao.selecionar(codigo);
            if (usuario == null) {
                JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado!");
                limpar();
            } else {
                limparSenhas();
                popularFormUsuario(usuario);
            }
        } catch (DaoException ex) {
            Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popularFormUsuario(UsuarioBean usuario) {
        ProfessorDao pd = new ProfessorDao();
        ArrayList<ProfessorBean> professores;
        try {
            professores = (ArrayList<ProfessorBean>) pd.listar();
            for (int i = 0; i < professores.size(); i++) {
                if (professores.get(i).getId().equals(usuario.getFuncionario().getId()) && professores.get(i).getNome().equals(usuario.getFuncionario().getNome())) {
                    jCBFuncionario.setSelectedIndex(i);
                }
            }
        } catch (DaoException ex) {
            Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PerfilDao perfil = new PerfilDao();
        ArrayList<PerfilBean> perfis;
        try {
            perfis = (ArrayList<PerfilBean>) perfil.listar();
            for (int i = 0; i < perfis.size(); i++) {
                if (perfis.get(i).getId().equals(usuario.getPerfil().getId()) && perfis.get(i).getTipoPerfil().equals(usuario.getPerfil().getTipoPerfil())) {
                    jCBPerfil.setSelectedIndex(i);
                }
            }
        } catch (DaoException ex) {
            Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTFCodigo.setText(usuario.getId().toString());
        jTFUsuario.setText(usuario.getUsuario());
    }

    private void alterar() {
        UsuarioBean usuario = populaLoginBean2();

        if (usuario != null) {
            try {
                if (usuarioDao.alterar(usuario) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Usuário alterado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao alterar!");
                }
            } catch (DaoException ex) {
                Logger.getLogger(JIFCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private UsuarioBean populaLoginBean2() {
        UsuarioBean usuario;
        FuncionarioBean funcionario;

        if (validaLogin()) {
            usuario = new UsuarioBean();
            funcionario = (FuncionarioBean) jCBFuncionario.getSelectedItem();
            
            PerfilBean perfil = (PerfilBean) jCBPerfil.getSelectedItem();
            
            usuario.setId(Integer.parseInt(jTFCodigo.getText()));
            usuario.setFuncionario(funcionario);
            usuario.setPerfil(perfil);
            usuario.setUsuario(jTFUsuario.getText());
            usuario.setSenha(FrameWork.criptografar(jPFSenha.getText()));

            return usuario;
        }
        return null;
    }

    

}
